# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_github_packages:
  - jimhester/covr

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.2
      brew_packages: cairo

r:
 - oldrel
 - release
 - devel

after_success:
  - Rscript -e 'library(covr);codecov()'
