# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_github_packages:
  - jimhester/covr

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: linux
      dist: trusty
      r: devel
    - os: linux
      dist: xenial
      r: devel
    - os: osx
      osx_image: beta-xcode6.1

after_success:
  - Rscript -e 'library(covr);codecov()'
